
$customerEquipment = @(
    @{ Manufacturer = "Microsoft"; Model = "Windows"; ClientsAffected = "ClientA" },
    @{ Manufacturer = "Cisco"; Model = "asa"; ClientsAffected = "ClientB" },
    @{ Manufacturer = "Sophos"; Model = "XG 116"; ClientsAffected = "ClientC" },
    @{ Manufacturer = "Sophos"; Model = "XG 136"; ClientsAffected = "ClientD" },
    @{ Manufacturer = "Sophos"; Model = "XG 210"; ClientsAffected = "ClientE" },
    @{ Manufacturer = "Sophos"; Model = "XG 230"; ClientsAffected = "ClientF" },
    @{ Manufacturer = "Sophos"; Model = "XG 310"; ClientsAffected = "ClientG" },
    @{ Manufacturer = "Sophos"; Model = "XG 330"; ClientsAffected = "ClientH" },
    @{ Manufacturer = "Sophos"; Model = "XG 430"; ClientsAffected = "ClientI" },
    @{ Manufacturer = "Sophos"; Model = "XG 450"; ClientsAffected = "ClientJ" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Controller"; ClientsAffected = "ClientK" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch Gen2"; ClientsAffected = "ClientL" },
    @{ Manufacturer = "Ubiquiti"; Model = "USG"; ClientsAffected = "ClientM" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch 8"; ClientsAffected = "ClientN" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch 16"; ClientsAffected = "ClientO" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch 24"; ClientsAffected = "ClientP" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch 48"; ClientsAffected = "ClientQ" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch Pro 24"; ClientsAffected = "ClientR" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch Pro 48"; ClientsAffected = "ClientS" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch Lite 8"; ClientsAffected = "ClientT" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch Lite 16"; ClientsAffected = "ClientU" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch Lite 24"; ClientsAffected = "ClientV" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch Lite 48"; ClientsAffected = "ClientW" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch Flex"; ClientsAffected = "ClientX" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch Flex Mini"; ClientsAffected = "ClientY" },
    @{ Manufacturer = "Ubiquiti"; Model = "UniFi Switch Flex XG"; ClientsAffected = "ClientZ" }
)